/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule BrowseQuestionsQuery.graphql
 * @generated SignedSource<<fe50399e7ca3b7ad8af26a8be26ff233>>
 * @relayHash 2f9216b031608e26ccc99203beef55c6
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query BrowseQuestionsQuery {
  questions {
    id
    title
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "BrowseQuestionsQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "question",
        "name": "questions",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "title",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "BrowseQuestionsQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "BrowseQuestionsQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "question",
        "name": "questions",
        "plural": true,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "title",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query BrowseQuestionsQuery {\n  questions {\n    id\n    title\n  }\n}\n"
};

module.exports = batch;
